############# English navigation ##############

# main menu
[[main]]

[[main]]
name = "Services"
weight = 1

[[main]]
parent = "Services"
name = "Automatisierung"
url = "#automation"

[[main]]
parent = "Services"
name = "Bots"
url = "#bots"

[[main]]
parent = "Services"
name = "Devops"
url = "#devops"

[[main]]
name = "About"
url = "/about"
weight = 2

# [[main]]
# weight = 4
# name = "Blog"

# [[main]]
# parent = "Blog"
# name = "BlogPage"
# url = "/blog"

# [[main]]
# parent = "Blog"
# name = "Elements"
# url = "/elements"

# [[main]]
# parent = "Pages"
# name = "Contact"
# url = "/contact"

# [[main]]
# parent = "Pages"
# name = "Authors"
# url = "/authors"

# [[main]]
# parent = "Pages"
# name = "Categories"
# url = "/categories"

# [[main]]
# parent = "Pages"
# name = "404 Page"
# url = "/404"


# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "About"
url = "/about"
weight = 2

[[footer]]
name = "Imprint"
url = "/imprint"
weight = 3

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 4
